### PR TITLE
Add certificate no column

### PR DESCRIPTION
**Pull request by lovepoem**

### CODE REVIEW

**Comment by zhaofeng-shu33** [comment]
Currently, our backend has only two status: everything is ok (success) and something is wrong (fail). We should consider more detailed return message.

**Comment by lovepoem** [comment]
Does the number column mean "certificate No" ?

**Comment by zhaofeng-shu33** [comment]
Yes

**Comment by lovepoem** [comment]
> Yes
ok, I add it to the README

**Pull request merged**
