### PR TITLE
Add calibreapp-image-actions

### PR DESCRIPTION
**Pull request by chenrui333**
Same as https://github.com/wuhan2020/wuhan2020.github.io/pull/232

### CODE REVIEW

**Comment by chenrui333** [comment]
@zhaofeng-shu33 dont worry too much (this is just like double guard) 😄

**Comment by chenrui333** [comment]
Just realized that we actually can improve the github action triggers as well.

**Comment by chenrui333** [comment]
@zhaofeng-shu33 as you can see, this image action still have value over imgbot (the image still got optimized)

**Comment by zhaofeng-shu33** [comment]
> @zhaofeng-shu33 dont worry too much (this is just like double guard)

Maybe this action should only be run when PR is merged into master branch?

**Comment by chenrui333** [comment]
One sec, let me improve the action trigger little bit.

**Pull request merged**
