### PR TITLE
Xiaozhua send notice email

### PR DESCRIPTION
**Pull request by youqingxiaozhua**
整理数据库操作为model.py
new feature：新增为status为0的用户发送通知邮件

### CODE REVIEW

**Comment by lovepoem** [comment]
Good job

**Comment by zhaofeng-shu33** [comment]
Why there are two files ` API/pic_email.py` and `pic_email.py`?

**Comment by youqingxiaozhua** [comment]
> Why there are two files ` API/pic_email.py` and `pic_email.py`?

 It's a problem inherited from history, I just refactored the code and it seems to work well.

**Comment by youqingxiaozhua** [comment]
#12

**Comment by lovepoem** [comment]
需要把README.md和API/README.md合并下

**Comment by zhaofeng-shu33** [comment]
> 需要把README.md和API/README.md合并下

**Pull request merged**
